name: CI - ETL (python cronjob)

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  docker-build-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase GHCR owner
        shell: bash
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ETL image
        uses: docker/build-push-action@v6
        with:
          context: ./python-project
          push: false
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/devopscase-etl:ci
  k8s-validate-etl:
    runs-on: ubuntu-latest
    needs: docker-build-etl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz kubeconform
          sudo mv kubeconform /usr/local/bin/kubeconform
          kubeconform -v

      - name: Validate ETL CronJob manifest (schema validation)
        run: |
          kubeconform -strict -ignore-missing-schemas -summary \
            -kubernetes-version 1.29.0 \
            k8s/etl-cronjob.yaml

  
